{
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "cve@mitre.org",
            "ID": "CVE-2021-41325",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "n/a",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "n/a"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "Broken access control for user creation in Pydio Cells 2.2.9 allows remote anonymous users to create standard users via the profile parameter. (In addition, such users can be granted several admin permissions via the Roles parameter.)"
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "n/a"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://pydio.com/fr/community/releases/pydio-cells/pydio-cells-enterprise-2212",
                    "refsource": "MISC",
                    "url": "https://pydio.com/fr/community/releases/pydio-cells/pydio-cells-enterprise-2212"
                },
                {
                    "name": "https://github.com/pydio/cells/releases/tag/v2.2.12",
                    "refsource": "MISC",
                    "url": "https://github.com/pydio/cells/releases/tag/v2.2.12"
                },
                {
                    "name": "https://charonv.net/Pydio-Broken-Access-Control/",
                    "refsource": "MISC",
                    "url": "https://charonv.net/Pydio-Broken-Access-Control/"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@mitre.org",
                "ID": "CVE-2021-41325"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "Broken access control for user creation in Pydio Cells 2.2.9 allows remote anonymous users to create standard users via the profile parameter. (In addition, such users can be granted several admin permissions via the Roles parameter.)"
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://github.com/pydio/cells/releases/tag/v2.2.12",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://github.com/pydio/cells/releases/tag/v2.2.12"
                    },
                    {
                        "name": "https://pydio.com/fr/community/releases/pydio-cells/pydio-cells-enterprise-2212",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://pydio.com/fr/community/releases/pydio-cells/pydio-cells-enterprise-2212"
                    },
                    {
                        "name": "https://charonv.net/Pydio-Broken-Access-Control/",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://charonv.net/Pydio-Broken-Access-Control/"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-09-30T19:43Z",
        "publishedDate": "2021-09-30T19:15Z"
    }
}