{
    "DWF": {
        "references": [
            "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2021-32029",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1956883",
            "https://www.suse.com/security/cve/CVE-2021-32029/",
            "https://ubuntu.com/security/CVE-2021-32029",
            "https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-32029",
            "https://security.alpinelinux.org/vuln/CVE-2021-32029",
            "https://security.archlinux.org/CVE-2021-32029"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "secalert@redhat.com",
            "ID": "CVE-2021-32029",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "postgresql",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "postgresql 13.3, postgresql 12.7, postgresql 11.12"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "A flaw was found in postgresql. Using an UPDATE ... RETURNING command on a purpose-crafted table, an authenticated database user could read arbitrary bytes of server memory. The highest threat from this vulnerability is to data confidentiality."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "CWE-200"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1956883",
                    "refsource": "MISC",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1956883"
                },
                {
                    "name": "https://www.postgresql.org/support/security/CVE-2021-32029/",
                    "refsource": "MISC",
                    "url": "https://www.postgresql.org/support/security/CVE-2021-32029/"
                }
            ]
        }
    }
}